projects/counter/index.html

Added functionality to handle long press events for incrementing and decrementing the counter in the HTML-based counter component.
- Added `setInterval` and `clearInterval` to continuously update the counter on long press of the `+` and `-` buttons.
- Ensured compatibility with both desktop (mouse events) and mobile devices (touch events).
1. Press and hold the `+` or `-` button.
2. Observe the counter increasing or decreasing continuously while the button is held.
3. Release the button to stop the counting.
4. Works on both desktop and mobile.

increase or decrease count when you long-press the + and - buttons

---

community/frontend/index.html
index.html
projects/Love Calculator/style.css

[Screencast from 05-10-24 05:09:23 PM IST.webm](https://github.com/user-attachments/assets/4c6f3482-9346-4222-aaf8-5b0c95a38c3f)
The url in the anchor tag is fixed and it is successfully redirecting to the Generate Gradient Project when the Generate Gradient Button is clicked.

Fixed issue #326: Generate Gradient Button redirection fixed

---

projects/githubProfileViewer/index.html

Changes I did remove the **_Document_** from <title> added **GitHub Profile Viewer** to <title>
**BEFORE** ❌❌
**AFTER** ✅✅
Fixed the Issue #490
Please give me hacktober and hacktober-accepted labels

Updated the GitHub Profile Viewer

---

projects/bmi calculator/index.html

fixes: #487
Changed label of height parameter **_"m"_**  to **_"cm"_** in BMI Calculator.

Updated: "m" to "cm" in BMI Calculator

---

community/frontend/index.html
index.html

There was a mistake in the anchor tag for the Number Guessing element in the Home page of the project, that's why when any user clicks the button to get to the game, it is redirecting them to a not found page.
The wrong redirected page URL was: `https://master-web-development.netlify.app/projects/Number%20guessinguessing/index.html` .
But the correct URL should be : `https://master-web-development.netlify.app/projects/Number%20guessing/index.html`.
So, I fixed the issue by changing the href in the anchor tag of the index.html or the home page of the project, And now it works fine, as it should be.
Thank you for giving me this opportunity to contribute to your repository. Also kindly assign the gssoc-ext and hacktoberfest labels with the PR.
I'm also attaching the screen recording of the …

Fixed issue #330: Wrong Redirection in Home Page for Number Guessing game

---

projects/Inbox_Master/.vscode/settings.json
projects/Inbox_Master/index.html
projects/Inbox_Master/script.js
projects/Inbox_Master/style.css

Added inbox master project

---

css/style.css
js/app.js

fixes : #1424 
https://github.com/user-attachments/assets/36c866e4-df70-4cfc-a570-95aa2e89d734

suggestion functionality added in search bar

---

Sorting Visualizer/index.html
Sorting Visualizer/script.js

Added the two algorithms that is  merge sort and quick sort  in sorting visulizer
#1405  issue solved

Added the two algorithms that is  merge sort and quick sort 

---

projects/Word Ladder Puzzle Game/index.html
projects/Word Ladder Puzzle Game/script.js
projects/Word Ladder Puzzle Game/style.css

Issue #1555 
Successfully added the word ladder puzzle game with clean code and comments for the user to understand.
https://github.com/user-attachments/assets/fceaf686-a197-49ae-b7a2-ba6ffc8f7ff9

#1555 Added the Word Ladder Puzzle Game

---

projects/Crowd Source Escape Room/index.html
projects/Crowd Source Escape Room/script.js
projects/Crowd Source Escape Room/styles.css

Solves :- #1597 
🔴 Title : Inserting Crowdsource Escape Room.
🔴 Tech stack : HTML / CSS / JS
🔴 Objective : Create a web-based escape room game where users can design their own puzzles and challenges.
🔴 Summary : Others can play through these user-generated rooms, and you can use a leaderboard to foster competition.

Issue #1597 Solved :- Inserted Crowd Source Escape Room

---

css/style.css
index.html

FIxed the cards to take proper width

---

projects/Eco-friendly Decision Maker/index.html
projects/Eco-friendly Decision Maker/script.js
projects/Eco-friendly Decision Maker/styles.css

🔴 Title : Eco-friendly Decsision Maker
🔴 Tech stack : HTML / CSS / JS
🔴 Objective :Create a web tool that helps users make environmentally friendly decisions. Users can input their choices (like transportation, shopping, etc.), and the app calculates the carbon footprint and suggests greener alternatives, using a gamified approach .
🔴 Summary It :encourages eco-friendly habits. just input some good logic in Js and just provide code of web app

Issue - #1602 Solved - Added Eco-friendly Decision Maker

---

projects/File Downloader/index.html
projects/File Downloader/script.js
projects/File Downloader/style.css

Added File Downloader

---

projects/Real-time-device-tracker/README.md
projects/Real-time-device-tracker/app.js
projects/Real-time-device-tracker/package-lock.json
projects/Real-time-device-tracker/package.json
projects/Real-time-device-tracker/public/css/style.css
projects/Real-time-device-tracker/public/js/script.js
projects/Real-time-device-tracker/views/index.ejs

I have added a realtime device tracker | Issue #1623
This is a mini project for tracking a device connected to our app in real-time. Similar to online delivery apps where you can see the rider's current location, this app smoothly tracks and displays your location continuously.
- Node.js
- Express
- EJS
- Socket.io
- Leaflet
- OpenStreetMap
1. **Check for Geolocation Support**: Verify if the browser supports geolocation.
2. **Set Geolocation Options**: Configure options for high accuracy, a 5-second timeout, and no caching.
3. **Track User Location**: Use `watchPosition` to continuously track the user's location.
4. **Emit Location Data**: Emit latitude and longitude via a socket with the event "send-location". Log any errors to the console.
5. **Initialize the Map**: Center the map at …

Add realtime device tracker | Issue #1623

---

index.html
terms.html

Fixed issue #1564 
**Description**
This PR addresses the Updation of footer links to the new Terms of Use page and created a separate page for Terms of Use.
**Video**
https://github.com/user-attachments/assets/93a542ad-7329-4509-8fca-74b5617053ef
How I Solved It:
- Identified the broken link in the footer of the website.
- Created a new Terms of Use page.
- Updated the footer to link to the new Terms of Use page.

Created Terms of Use page

---

projects/Memory Tiles/css/flipnormal.css

🔴 Description: Resized game tiles to reduce scrolling and improve visibility, ensuring smoother gameplay without disrupting user experience.
🔴 Images/Videos:
Before:
[before-tiles.webm](https://github.com/user-attachments/assets/d4129460-a3d6-4e2e-8164-5065a5414fc8)
After:

Reduce Unnecessary Scrolling in Memory Tile Game 

---

css/style.css

The text on buttons under the title Organize projects previously was not visible. Thus I changed the colour scheme of the button as well as hover in a way that it suits both light as well as dark mode and matches with the colour scheme of the website.
Fixes#1993
Before:
After:
I hope the constribution made was useful!

Colour scheme changed under the title Organize project changed

---

Checkbox Carnival game/index.html
Checkbox Carnival game/style.css

📃: Checkbox Carnival game #2209 
Closes: #2209

 📃: Checkbox Carnival game #2209 

---

index.html

Fixes: #2181 
On clicking on gaming tool we will redirect to another website 
@iamrahulmahato Please review my change and let me know if need any change

Fix 404 error in gaming tool

---

index.html

Fixed the issue where the cards weren't displayed properly in their format of 3xN i.e. three cards per row. Initially, the first few cards were displayed correctly but later as the user scrolled along the cards weren't displayed correctly and the cards were displayed all in a single line.
- Fixes issue: #2315 
BEFORE:
AFTER:

[FIXED] [BUG] Cards not displayed correctly on homepage #2315

---

css/style.css

issue #2307 
in both mode the logo is visible perfect...
@iamrahulmahato sir merge it

fix the navbar issue #2307

---

Basic-Typing-Game/index.html
Basic-Typing-Game/script.js
Basic-Typing-Game/style.css

This is a basic typing game using HTML, CSS and JS. This project help to how use event handler of typing and local storage in web browser.

Add a new project of basic typing game

---

Mind_Walk_Game/index.html
Mind_Walk_Game/main.js
Mind_Walk_Game/readme.md
Mind_Walk_Game/style.css

MindMaze Challenge, a simple web-based game where you can test your guessing skills! Try and guess a random number between 1 and 100 with only 10 attempts.
1. Open the MindMaze Challenge website.
2. Enter your guess in the input field.
3. Click the "Submit Guess" button.
4. Receive feedback on your guess – whether it's too
5. high, too low, or correct.
6. Keep guessing until you either find the correct
7. number or run out of attempts.
. Randomly generated number for each round
. Track your previous guesses and the remaining attempts
. Enjoy a simple and interactive interface
. HTML
. CSS
. JavaScript

Add New Project - Mind Walk #340

---

projects/Tic-tac-toe/style.css

i added some new aesthetic color gradients to the backgrounds of the tic-tac-toe project to make it more attractive...
i did it in githun.dev...........but the file changes is just showing only abt few changes........

Sanyuktha prabhu patch 1

---

popup.js

Improved the Subscribe letter form !!

---

index.html

Before there were two headers and even some part of source was visible but now it has been resolved and only a single header is present that enhances the User Interface as header is one of the major component of any website. Even removed some of the duplicated game cards present on the Website.
Closes:
#2399 Duplication of Header

Duplication of Header Resolved

---

challenges/index.html
challenges/jseasy.html

Created a JS Easy Quiz challenge !!

---

challenges/jsmed.html

Created  JS Medium Challenge !!

---

Financial Insights Dashboard: Personal Finance Manager/app.js
Financial Insights Dashboard: Personal Finance Manager/chart.js
Financial Insights Dashboard: Personal Finance Manager/pfid.html
Financial Insights Dashboard: Personal Finance Manager/style.css

Personal Finance Dashboard: Comprehensive Financial Management tool
Personal Finance Dashboard, is a web-based application designed to help users efficiently manage and visualize their personal finances. It features tools for budgeting, expense tracking, savings goal monitoring, investment tracking, and financial insights. Built with HTML, CSS, JavaScript, and data visualization libraries like Chart.js, the dashboard provides a comprehensive and interactive way for users to understand and control their spending patterns and financial goals.
The project introduces a modular structure with interactive sections:
- Budgeting: Users can set a monthly budget and track spending progress.
- Expense Tracking: Daily expenses can be logged and categorized, providing a clear picture of spending …

[Updated] Personal Finance Dashboard: Comprehensive Financial Management Tool
