projects/Tic-tac-toe/app.js

tic tac toe tie popup added

---

projects/Calculator/index.html
projects/Calculator/style.css

I have updated the simple calculator to scientific calculator by adding functionalities of trig and inverse trig and also many other scientific functionalities.

Calculator Updated

---

index.html
projects/Number guessing/index.html
projects/Number guessing/script.js
projects/Number guessing/style.css

-- Added pic for feature in card
-- made a Number guessing( Html , css , mostly used Javascript
--updated readme file
issue no - #57 @justynigam

Added "Number_guessing" feature

---

projects/counter/index.html
projects/counter/style.css

**### Issue**- To Make COUNTER More Effective #61
To add Styling to "+", "-" Button
Also want add feature like to take input "+", "-" from Keyboard.

input from keyboard

---

projects/Sticky-Note/README.md
projects/Sticky-Note/index.html
projects/Sticky-Note/script.js
projects/Sticky-Note/style.css

#79 This pull request adds the functionality and styling for the Sticky Notes web application. It includes the creation, editing, and deletion of notes, as well as the basic CSS styles for the notes and the overall layout. The pull request also updates the README file with instructions on how to run the application locally.

 Sticky Notes Application

---

projects/Snake Game/README.md
projects/Snake Game/index.html
projects/Snake Game/script.js
projects/Snake Game/style.css

From improving the script to making the ui more minimalistic ; I have completely changed the game from its previous version; Check the deployment at https://riteshs1.github.io/Snake-Game/
before:
after:

Corrected Snake Game

---

projects/Hexsweep-Game/README.md
projects/Hexsweep-Game/index.html
projects/Hexsweep-Game/script.js
projects/Hexsweep-Game/styles.css

#103 
https://github.com/user-attachments/assets/21e89757-1cdc-4cd9-977c-c41d44da21d9

Added Hexsweep Game

---

css/style.css
index.html
js/app.js

Weather section added

---

projects/Bitcoin Detector/css/style.css
projects/Bitcoin Detector/html/index.html
projects/Bitcoin Detector/js/api.js
projects/Bitcoin Detector/js/chart.js
projects/Bitcoin Detector/js/dropdown.js
projects/Bitcoin Detector/js/time.js
projects/Bitcoin Detector/js/wallet.js

Added bitcoin price detector

---

projects/Plants/index.html

Thank you so much @iamrahulmahato for giving me this chance. As mentioned in issue number #162 I have added more information about all the planets. 
I have attached two samples below. Please review my pull request. Any feedback and suggestions are welcomed.

Added more information about the planets. #162

---

projects/Password Generator/index.html
projects/Password Generator/script.js

Issue #135 
here I added a custom input for the password 1-50 length  and a button to copy the text

Added Custom password Length and copy button

---

projects/Hangman/index.html
projects/Hangman/script.js
projects/Hangman/styles.css

Hangman is a word game where one player guesses letters to solve a word chosen by another player. If the player guessing makes a wrong guess, the other player draws a part of a person being hanged. The game is over when the person being hanged is complete.

Added a Hangman Game Project

---

projects/Doodle Draw/index.html
projects/Doodle Draw/manifest.json
projects/Doodle Draw/script.js
projects/Doodle Draw/styles.css

added doodles

---

css/style.css

feel free to say any changes and can you add hactoberfest tag too. Thank you!
issue: https://github.com/iamrahulmahato/master-web-development/issues/245

Dark Mode Card UI updated

---

projects/counter/style.css

- Icon background added when click happens.
- Plus/Minus icon scales little bit when clicks.

[FIX] Counter icon animation added

---

projects/timerapp/timer/index.html
projects/timerapp/timer/script.js
projects/timerapp/timer/style.css

A simple and intuitive design for easy navigation and usage, ensuring a great user experience timer application has been created.
It has reset feature capabilities in it.
@iamrahulmahato Please check it.

Timer application feature - issue #154

---

projects/Stop Watch/index.html
projects/Stop Watch/script.js
projects/Stop Watch/style.css

Enhanced the overall appearance of the stopwatch by applying a sleek dark theme with smooth, rounded buttons for improved user experience.
Updated the start and reset buttons with green and grey tones, respectively, for clear distinction and added hover effects for better interactivity.
Implemented a minimalist display for laps with an elegant font and alignment to maintain consistency with the dark theme.
Refined the time display to make it more prominent, focusing on readability.
Ensured the layout remains responsive across different screen sizes for optimal user interaction.

Improve Stopwatch UI with Modern Dark Theme and Interactive Buttons

---

index.html

As mentioned in issue number #246 , I have corrected the Wordle game title and description. 
@Tapabrata-Goswami @iamrahulmahato

Wordle game title corrected #246

---

projects/Drawing-Board/index.html
projects/Drawing-Board/script.js
projects/Drawing-Board/style.css

This pull request introduces a new drawing board project (Issue: #255), enabling users to create and manipulate drawings on a web canvas. The project consists of HTML, CSS, and JavaScript components designed for a seamless and interactive user experience.
**Features:**
- **Drawing Canvas**: Users can draw freely on an 800x700 canvas using their mouse.
- **Brush Size Control**: Buttons to increase or decrease the brush size, with a maximum size limit.
- **Color Picker**: A color input that allows users to select their desired drawing color.
- **Clear Canvas**: A button to clear the canvas for a fresh start.
**Implementation Details:**
- The HTML structure includes a canvas element and a toolbox for user controls.
- CSS styles enhance the visual aesthetics and usability of the application. …

Add drawing board project

---

css/style.css
index.html
js/app.js

Fixes #225 
Description:
This pull request adds a Scroll to Top button to improve the user experience. The button appears when the user scrolls down and allows them to easily return to the top of the page.
Changes Made:
Added a "Scroll to Top" button that becomes visible after scrolling down.
The button smoothly scrolls the page back to the top when clicked.
It fades in and out depending on the scroll position.
The button works with both light and dark themes and includes a simple floating animation to make it stand out.
Files Updated:
HTML: Added the button element.
CSS: Styled the button to match the theme and added animations.
JavaScript: Implemented the show/hide functionality and smooth scrolling.
Video:
https://github.com/user-attachments/assets/526385d3-de9a-4a44-90db-2452531e1da7

add scroll to top button

---

projects/counter/index.html

- Fixes #257 
- Now the counting is accurate.
- Now user can interact with keyboard butttons to count
- Arrow Up and Right key for increament.
- Arrow Down and Left key for decrement.

[FIX] Counting error fixed

---

projects/Plants/index.html

I have added more descriptive and precise information in this file.

index.html

---

projects/youtube/index.html
projects/youtube/script.js
projects/youtube/styles.css

@iamrahulmahato I have created a Youtube clone using HTML , CSS and JS
I have resolved the issue #157.

Youtube clone - issue #157 resolved

---

css/style.css
index.html
projects/random user generator/index.css
projects/random user generator/index.html
projects/random user generator/index.js

fixes #410  Added border radius to the images of card to give it a soft touch to eyes and also weather icon was looking terrible with white spaces being seen so fixed it also.

Issue #410 resolved : Card changes

---

css/style.css
index.html
projects/random user generator/index.css
projects/random user generator/index.html
projects/random user generator/index.js

fixes #413  Added simple yet effective scale hover effect on the cards to improve UI of the website

Issue #413 resolved : Hover effect

---

projects/Tic-tac-toe/style.css

This PR enhances the user interface (UI) for the Tic-Tac-Toe app to provide a more modern, user-friendly experience. The updated design improves overall usability and aesthetics, creating a smoother and more engaging gameplay experience.
here is the output before and after

enhanced ui for tic tac toe

---

index.html

Fixes #370  I update the URL and Generate Gradient working fine

Solved Issue #370 Generate Gradient not working

---

README.md

Fix #343 , I add a contribute section, where everyone can see who contribute in this repository.

Add contribute section

---

index.html

Fix #376 ,This feature will open the website in a new website.

Add target blank , open the website in a new tab

---

projects/Fruit Slicer/index.html
projects/Fruit Slicer/script.js
projects/Fruit Slicer/styles.css

Added fruit Slicer 
ISSUE no - #423 fixed

Added Fruit Slicer game

---

projects/Password Generator/index.html
projects/Password Generator/script.js
projects/Password Generator/style.css

This pull request enhances the Password Generator application with several new features and improvements to the user interface.
1. Added a password strength meter that updates in real-time
2. Implemented a more robust password generation algorithm
3. Enhanced character type selection with checkboxes
4. Improved error handling and user feedback
1. Updated CSS for a more professional look
2. Added visual feedback for password strength (color-coded meter)
3. Improved layout and responsiveness
#485
This update significantly improves the functionality and user experience of the Password Generator application.

Enhance Password Generator with Strength Meter and Improved UI

---

index.html

Issue no #419
hello PA,
I have added the favicon icon properly.

Favicon added

---

projects/feedbck_form/pro.html
projects/feedbck_form/style.css

file is added

---

projects/personal_finance_dashboard/index.html
projects/personal_finance_dashboard/script.js
projects/personal_finance_dashboard/styles.css

Added a project for a personal finance dashboard for gssoc-extd made with html css and javascript which is flexible i.e suitable for both mobile and desktop view.

added personal_finance_dashboard project issue no. 459

---

projects/Ping Pong Game/script.js

Fix #377 , Fix the bug in Ping Pong game.

Bug Fix in Ping Pong

---

projects/loan_calculator/index.html
projects/loan_calculator/style.css

<h2>Issue No :- #559 </h2>
<h3>successfully added loan calculator. </h3>

added loan calculator

---

css/style.css
index.html

#Issue
#600
This PR addresses a minor HTML issue in the `index.html` file:
- Adds the missing closing `</p>` tag in the Stick Hero card's description
- Ensures proper structure and formatting for the Stick Hero card

Fix: Add missing closing tag in Stick Hero card

---

projects/Ping Pong Game/index.html
projects/Ping Pong Game/script.js
projects/Ping Pong Game/style.css

#486
Add animations and game over condition to improve user experience.
- **HTML**: Add game over message element
- **CSS**: 
- Implement animations for game board, paddles, ball, and scores
- Add styles for game over message
- **JS**:
- Implement game over logic (10 points to win)
- Add score change animations
- Update game start/reset functions
- Verified animations and game over functionality
- Tested game restart after completion

Update Ping Pong Game

---

projects/Sudoko Solver/Readme.md
projects/Sudoko Solver/index.html
projects/Sudoko Solver/script.js
projects/Sudoko Solver/style.css

Added Sudoko Solver

---

projects/PACKABUNCHAS/README.md
projects/PACKABUNCHAS/game.js
projects/PACKABUNCHAS/index.html
projects/PACKABUNCHAS/style.css

ISSUE :- #213 
https://github.com/user-attachments/assets/2f08218b-92be-4343-8c97-fac13772e7d5

added   `PACKABUNCHAS` game

---

projects/random user generator/index.css
projects/random user generator/index.html
projects/random user generator/index.js

As mentioned in the issue #328 I added a user photo to display whenever the Next User Button is pressed.
Previously my PR got a merge conflict, hope this time it don't get one.
The screen recording of the project after my fix is attached below.
[Screencast from 06-10-24 11:53:45 PM IST.webm](https://github.com/user-attachments/assets/9e74546e-d9f1-4b99-9492-32957aa9ad17)

Fixed the issue #328: Added Image in Random User Generator

---

projects/WordSearch Game/index.html
projects/WordSearch Game/script.js
projects/WordSearch Game/styles.css

Built using HTML, CSS, JS
HTML Structure (index.html):
Created a new HTML structure for the Word Search Game.
Added a container for the game elements, including the grid and the list of words to find.
Included a reset button to restart the game.
Linked the necessary CSS and JavaScript files for styling and functionality.
CSS Styling (styles.css):
Added styles for the Word Search Game container, grid, and word list.
Styled the reset button for better user interaction.
Ensured responsive design for different screen sizes.
JavaScript Functionality (script.js):
Implemented the logic for generating the word search grid.
Added functionality to highlight words when found.
Included a reset function to restart the game
Closes: #540

Added WordSearch Game

---

projects/Rock Paper Scissors/Styles.css
projects/Rock Paper Scissors/index.html
projects/Rock Paper Scissors/script.js

I have added computer choice feature to the existing game to make it more visually appealing. 
Fixed #621 
Check it out below:
https://github.com/user-attachments/assets/b040b920-a23a-44fd-af3a-e1bb8e401285

Added Computer Choice Feature

---

index.html

Fixed the broken website ui
https://github.com/user-attachments/assets/867ea45a-97bc-4ba7-b31e-14a139f77397

fix the website ui

---

projects/Todo List/index.html
projects/Todo List/script.js

Closes: #353 
**Description:**
This pull request adds a new feature to the ToDo App that allows users to search for tasks in both the pending and completed task lists. The search functionality dynamically filters the tasks based on the input provided by the user.
**Changes Included:**
-Added an input field for searching tasks in the HTML structure.
-Implemented JavaScript logic to dynamically filter tasks as the user types into the search box.
-Ensured that the tasks are hidden if they don't match the search query and re-displayed when the search input is cleared.
-The search works for both pending and completed tasks lists.
-Updated the task filtering logic to account for case-insensitive searches.
**ScreenShot**

Added task search functionality

---

projects/temprature_converter/index.html
projects/temprature_converter/style.css

Fixes #755 
Created a Simple Temprature Converter using HTML, CSS and Javascript.

Added a simple temprature converter

---

projects/weather/index.html
projects/weather/style.css

changed the weather app functionality

---

projects/Code Compiler/README.md
projects/Code Compiler/background.js
projects/Code Compiler/manifest.json
projects/Code Compiler/popup.html
projects/Code Compiler/popup.js
projects/Code Compiler/server.js

Added code editor

---

projects/counter/index.html
projects/counter/style.css

This enhancement aims to replace repetitive manual button presses with a digital one-click counter for faster and more efficient counting. It will reduce user effort and improve the app’s usability, particularly for tasks requiring quick or large-scale counts.
The main change in this pull request is the introduction of two new buttons: Start and Stop. These buttons allow users to initiate and halt automatic counting with ease. Once the Start button is pressed, the counter will increment automatically, eliminating the need for manual pressing of the plus and minus buttons. This enhancement simplifies user interaction, making the app more intuitive and efficient, as users no longer need to manually press buttons for counting, allowing them to focus on other tasks.
Attaching a visual for …

Transition to Digital One-Click Counter 

---

projects/Insect-Catch-Game/index.html
projects/Insect-Catch-Game/script.js
projects/Insect-Catch-Game/style.css

Solve :
Issue no #718 
Hey @iamrahulmahato 
Could you please upgrade this game to **level 2**? I believe it deserves this recognition as the project is a bit larger and slightly more challenging. The complexity and effort put into it warrant a higher level. Thank you!

Added Insect catch game : Issue no 718

---

projects/Tower Blocks/index.html
projects/Tower Blocks/script.js
projects/Tower Blocks/style.css

Solved : 
Issue no #873 
Hey @iamrahulmahato 
Please grant level 2 for this game because it required a lot of JavaScript code and was not easy to create. Thank you for your understanding.

Added Tower block game : Issue no #873

---

index.html

Fix: #941 
I have corrected the previously broken layout, please review:

Fix #941: Corrected Broken Layout

---

projects/Portfolio Builder/app.js
projects/Portfolio Builder/index.html
projects/Portfolio Builder/index.js
projects/Portfolio Builder/styles.css

I have added a **Portfolio Builder App** using **HTML, CSS, and JavaScript**. It allows users to input their details, display them on the screen, and download the portfolio as a PDF instantly.
Please review the **level label** before merging. If everything looks good, kindly proceed with the merge.
@iamrahulmahato 
Happy to contribute! 😊
issue #901

Added `Portfolio Builder` Project

---

projects/Color Guessing Game/script.js
projects/Color Guessing Game/style.css

🐞 : In Color Guessing after choosing a wrong color try again is not working. #876
before :- 
Means it is only showing new colors in button even if the answer is incorrect.
after :- 
Showing try again in the button when the answer is incorrect.
@iamrahulmahato Check this PR and merge this and assign this to me and put relevent labels like gssoc 2024 ext and hacktoberfest and level.

🐞 : In Color Guessing after choosing a wrong color try again is not working. #876

---

css/style.css

Adding hover effect for view source code button
This pull request closes #912 
Here I have added hover effect for view source code button 
When we hover on the button it's color changes and it's size increases

Adding hover effect for view source code button

---

projects/EduConnect/QuizAppGemini/package-lock.json
projects/EduConnect/QuizAppGemini/package.json

Reverts iamrahulmahato/master-web-development#985

Revert "Bump next from 14.0.4 to 14.2.10 in /projects/EduConnect/QuizAppGemini"

---

projects/EduConnect/QuizAppGemini/package-lock.json

Reverts iamrahulmahato/master-web-development#984

Revert "Bump braces from 3.0.2 to 3.0.3 in /projects/EduConnect/QuizAppGemini"

---

projects/Display_Test/index.html
projects/Display_Test/script.js
projects/Display_Test/style.css

This pull request addresses and resolves issue #953 by implementing the display test feature using HTML, CSS, and JavaScript. The feature is fully functional and enhances the user interface by providing a seamless display test experience.
**Key Changes:**
1. **HTML Structure:**
- Developed a semantic and accessible HTML structure to support the display test feature.
- Ensured the markup is clean and follows best practices for maintainability.
2. **Styling with CSS:**
- Designed a responsive and visually appealing layout using CSS.
- Implemented styles that ensure compatibility across various devices and screen sizes.
3. **JavaScript Functionality:**
- Added JavaScript to handle dynamic interactions and enhance user experience.
- Ensured the script is optimized for performance and follows …

Complete Implementation of Display Test Feature Using HTML, CSS, and JavaScript (#953)

---

projects/githubProfileViewer/index.html
projects/githubProfileViewer/script.js
projects/githubProfileViewer/style.css

Added username not found error handling

---

projects/Todo List/style.css

I have improved the styling of ToDo App. The comparion is shown below:
#952 completed
Before: 
After:

 🧑‍💻 : improve the styling of ToDo App #952 

---

css/style.css

Customised the scrollbar 
completed #816 
Commit 1 :
Commit 2 :

Scrollbar Customisation | Issue #816

---

projects/Jigsaw_Puzzle/Readme.md
projects/Jigsaw_Puzzle/index.html
projects/Jigsaw_Puzzle/script.js
projects/Jigsaw_Puzzle/style.css

Added Jigsaw_Puzzle.
Closes #844

Added Jigsaw_Puzzle

---

projects/Travel Vlog/home.html

Added Style to the button 
Techstack:CSS3
Before Commit
After Commit

Button Alignment Issue #989

---

projects/Todo List/index.html
projects/Todo List/script.js

**closes:** #841 
**Description:**
This pull request ensures that both task lists within the ToDo app can dynamically manage height, providing a scrolling feature when task lists exceed a defined height limit. This adjustment helps maintain an optimal layout without compromising accessibility.
**ScreenShot:**
https://github.com/user-attachments/assets/5349c9dd-33fa-40c9-9b7f-c9c13f3aab18

Add Dynamic Height Management to Task Lists

---

projects/N-Queen-Visualiser/README.md
projects/N-Queen-Visualiser/chess.js
projects/N-Queen-Visualiser/index.css
projects/N-Queen-Visualiser/index.html

I have added N-Queen Visualiser 
Completed #699 
https://github.com/user-attachments/assets/0e4374d4-f204-49c3-ab59-7f2d3530d6c3

Addition of N-Queen | Issue #699

---

projects/McDonald's Ordering chatbot/main.py
projects/Movie recommendation system/ReadMe.md
projects/Movie recommendation system/main.py

Add  main.py which contains the code of McDonald's Ordering chatbot

Add main.py file

---

feedback.html
index.html

I have successfully added feedback form to your website.
Issue resolved: #956

Added feedback form

---

projects/Cow and Bull Game/index.html
projects/Cow and Bull Game/script.js
projects/Cow and Bull Game/style.css

Solution for Issue #372 
A new project (a game _Cow and Bull_) has been created in the projects folder.
Files created:
- index.html
- style.css
- script.js
Game flow:
- Player is provided with 10 tries to try and guess the randomly generated 4-digit number.
- Confetti is triggered with a congratulations message if player manages to guess within the guess limit.
- If not, the secret number is displayed and the player can reset to start a new game.
Screenshot of the UI:

Cow and Bull Game created - Issue #372

---

projects/Building Block/script.js

Isssue : #950 
Closes #950
I added the final score to be displayed after the user ends/looses the game, it helps to set their target while playing next time.
@iamrahulmahato please review and merge.

Added Final score board

---

projects/Clock/index.html
projects/Clock/script.js
projects/Clock/style.css

i have added option to display clock time from different timezones. The addition of new feature is shown below.
Before:
After:

 🧑‍💻 : add times of different zones/countries in Clock project #1025 

---

projects/Gesturevolume/gesture.py

As a contributor to the Hand Gesture Volume Control project, I developed a Python application that utilizes computer vision techniques to control system volume through hand gestures. This project leverages OpenCV and MediaPipe for real-time hand tracking, enabling users to adjust audio levels seamlessly through natural hand movements.
Key Contributions:
Real-time Hand Gesture Recognition: Implemented a robust hand detection system using MediaPipe, allowing for accurate tracking of hand positions and movements.
Dynamic Volume Control Logic: Developed a volume adjustment algorithm that translates the position of the user's hand into corresponding system volume levels, enabling smooth transitions from 0 to 100%.
Distance-Based Volume Adjustment: Designed a system where the height of the …

<Gesture via voume control>

---

projects/Hangman Game/scripts/script.js

Add Keyboard Input Functionality to Hangman Game #990

Add Keyboard Input Functionality to Hangman Game #990

---

projects/Ping Pong Game/index.html
projects/Ping Pong Game/script.js
projects/Ping Pong Game/style.css

i have added pause to the game and also add controls . Intially  the control was w s  .. after updating  .. i have added up and down arrows to the control .

Solve issue 1004

---

index.html

Added copyright stement!!
now the website looks complete

Added copyright in the footer of the website

---

projects/Lorem_ipsum/index.html
projects/Lorem_ipsum/script.js
projects/Lorem_ipsum/styles.css

Issue : #1074 
Changes:
1. Added a header
2. Updated the UI with a glossy effect
3. Added validation on button click
4. Added toast messages on button click

[Fix] : UI improvements for the Lorem Ipsum Generator #1074

---

README.md

I have updated the project list in the README file. I have expanded this list from **15 to a total of 90 projects**.
Additionally, I request to change the level  from **level 1  to level 2** because  it required more than 3+ hours of manual work, as I needed to insert the URLs for each project individually and make checks.
1. BEFORE: 
2. AFTER:

 Update Project List in README: Expanded from 15 to 90 Projects

---

index.html

issue resolved: #1161
spelling corrected.
Please add gssoc-extd, hacktoberfest and level label also.

spelling error corrected

---

projects/Love Calculator/index.html
projects/Love Calculator/script.js
projects/Love Calculator/style.css

issue resolved: #1083 
This is for both gssoc and hacktoberfest
Thanks!

added loading indicator after clicking calculate in love calculator project

---

projects/Eyes Follow Cursor/index.html
projects/Eyes Follow Cursor/script.js
projects/Eyes Follow Cursor/style.css

Added Eyes follow cursor

---

index.html

This pull request introduces a scroll button that enables smooth page-by-page scrolling on the website. The button is fixed in position and enhances user experience by allowing users to navigate through the content effortlessly. Upon clicking the button, the page scrolls down by the height of the viewport, creating a more engaging interaction.
Issue Number -> #1160 
Feature Enhancement
Before:
After:
Thank You :)

Added scroll down button

---

css/style.css

Hey @iamrahulmahato ,
Issue closes #1146.
I have changed the color and shape of the vertical scrollbar.
can you please merge it ?

Styled the color of vertical  scrollbar

---

index.html

PR #1169 
The website is a showcase of web development projects, but it lacks proper meta tags, heading hierarchy, image optimization, and schema markup. This makes it difficult for search engines to understand the content and structure of the site, resulting in poor search engine ranking.
This pull request aims to enhance the website's visibility and ranking on search engines by implementing proper SEO practices. The changes include:
Adding meta tags for title, description, and keywords to each page
Optimizing image attributes by adding descriptive alt text
Creating and submitting an XML sitemap to search engines
Implementing schema markup to provide search engines with more context about the content
These changes will improve the website's search engine ranking, drive more traffic to …

Implement SEO Improvements for Enhanced Search Engine Ranking

---

projects/Currency Convertor/style.css

Issue #1073 is now solved. The UI has been updated with a glossy effect, which looks cool.
@iamrahulmahato, you can now merge this PR.

[Fix] : UI FIX of currency converter project

---

css/style.css
index.html

closes issue #1106
https://github.com/user-attachments/assets/68d5cb8e-5bd4-4288-aa29-a375acb24d39

bug fix for dark mode toggler button

---

index.html
js/app.js

issue #812 solved
- Implemented a mouse cursor trail effect to improve user interaction on the website.
- This effect adds a dynamic visual element that follows the cursor, enhancing the user experience, especially on interactive sections like the home page.
- The effect has been optimized to ensure smooth performance and only appears where it adds value without overwhelming the user.
https://github.com/user-attachments/assets/95da296f-2b44-4eba-8a96-565efc734681

Added Mouse Cursor Trail Effect for Enhanced User Interaction

---

projects/Lights Out/index.html
projects/Lights Out/script.js
projects/Lights Out/style.css

fixes #1190 
This PR adds a lights out game to the projects section of the repository.
https://github.com/user-attachments/assets/e4e59f96-0809-4ed8-ae74-a9513a50cf6a

Add lights out game

---

projects/Analog Clock/index.html
projects/Analog Clock/script.js
projects/Analog Clock/style.css

Analog clock added

---

chatbot.html

issue resolved : #1269 
This is for both gssoc and hacktoberfest
Thanks!

users can send message to chatbot now by pressing enter

---

css/style.css
index.html

issue : #1307 
@iamrahulmahato ,I've fixed the issue please review it and if possible please label this issue fixing with 'gssoc-extd' and 'hacktoberfest-accepted'

fixed the alignment

---

projects/Responsive Neumorphic Calculator/index.html
projects/Responsive Neumorphic Calculator/style.css

This PR solves issue #1082 
Please do add the respective level labels.

Added Project

---

Sorting Visualizer/script.js

added script.js file for sorting visualizer

Issue #1311 (solved) Created script.js

---

Sorting Visualizer/style.css

added style.css for sorting visualizer

Issue #1311 (solved) Created style.css

---

Sorting Visualizer/index.html

i ave added index.html file for sorting visualizer

Issue #1311 (solved) Created index.html

---

projects/Personalized Cooking Guide/index.html
projects/Personalized Cooking Guide/script.js
projects/Personalized Cooking Guide/style.css

Issue #1323 Solved:-
🔴 Title : Personlized Cooking Guide
🔴 Tech stack : HTML , CSS , JS
🔴 Objective : Either input no of resources you have or it will give you various personalized recipes
🔴 Summary : It's great when you don't know what to eat today.

#1323 Issue Solved :- Personlized Cooking Guide Project Created.

---

css/style.css

fix #1263 
I have fixed the Visibility of Project Names.
As it will be in black in light Mode and White in dark Mode.

Fixed Visibility of Project names in Dark Mode

---

projects/Virtual Closet Organizer/index.html
projects/Virtual Closet Organizer/script.js
projects/Virtual Closet Organizer/style.css

Solves ISSUE  :- #1325 
🔴 Title:
Virtual Closet Organizer
🔴 Tech Stack:
Frontend: HTML, CSS, JavaScript
🔴 Objective:
The goal is to create a web-based virtual closet where users can upload images of their clothing, organize them, and create outfits using a simple drag-and-drop interface. This project aims to help users better manage their wardrobe and plan outfits conveniently.
🔴 Summary:
The Virtual Closet Organizer allows users to upload images of their clothes and categorize them into sections (tops, bottoms, shoes, accessories). Users can then create outfits by dragging clothing items into outfit slots (e.g., top, bottom, shoes).

#1325 Issue:- Solved - Virtual Closet Organiser

---

css/style.css

Resolved Issue #1277 
This pull request addresses the issue of the scrollbar's visibility and aesthetics on the webpage. The previous scrollbar design lacked distinct features, making it difficult to notice, especially during hover actions.
**The following changes were made to enhance the scrollbar's appearance:**
- **Color Change:** The scrollbar color was updated to match the overall theme of the webpage, ensuring better integration and visibility against the background.
- **Rounded Edges:** The scrollbar thumb was styled with rounded edges to create a smoother and more modern look.
- **Hover Effect:** A new hover effect was implemented, changing the thumb's color on mouse-over. This provides a clearer visual cue to users, enhancing the overall user experience.
- **Gradient Addition:** …

Updated scrollbar with gradient color, rounded edges, and hover effect

---

projects/DBMS_Quiz/index.html
projects/DBMS_Quiz/script.js
projects/DBMS_Quiz/styles.css

Added  DBMS Quiz Arena Project
Fixes #1334
🔴 Objective : To create an interactive quiz application that tests users' knowledge on Database Management Systems (DBMS) concepts, providing immediate feedback on their answers.
🔴 Screenshot:

Added DBMS_Quiz_Arena Project

---

js/app.js

Hey @iamrahulmahato , sorry for the delay. I have solved issue #858 . Kindly check my PR and merge it if everything is okay. Thanks!

theme toggling fixed

---

css/style.css

Fixed #1270 
Kindly add all tags while merging PR.

Text color fixed

---

projects/Nature Simulation/index.html
projects/Nature Simulation/script.js
projects/Nature Simulation/styles.css

ISSUE : - #1370
Nature SImulation  Game 
The Nature Simulation Game allows players to build and sustain an ecosystem by adding plants and animals, managing water and food resources, and responding to random environmental events. Players face win/lose conditions based on their ability to maintain balance within the ecosystem. With an engaging user interface and random challenges, the game provides a fun and educational experience about ecological dynamics
Thank you.

#1370 Solved - Awesome Game Added - Nature Simulation

---

projects/Habit Tracker App/index.html
projects/Habit Tracker App/script.js
projects/Habit Tracker App/styles.css
projects/Movie Review Sentiment Analyzer/index.html
projects/Movie Review Sentiment Analyzer/script.js
projects/Movie Review Sentiment Analyzer/styles.css

This pull request adds the complete implementation of the Movie Review Sentiment Analyzer project, built using HTML, CSS, and JavaScript. The tool analyzes user-submitted movie reviews and determines whether the sentiment is positive or negative.
Features
HTML & CSS: Provides a responsive user interface for entering and displaying review sentiment.
JavaScript Logic: Implements the core logic to classify reviews based on keywords.
Interactive Output: Displays sentiment results dynamically upon user input.
Changes
Added index.html for the structure of the web application.
Added styles.css to style the interface for a better user experience.
Added script.js containing the sentiment analysis logic.
Testing & Validation
Verified with multiple review samples for both positive and negative …

ISSUE #1374 Added new project Movie Review Sentiment Analyzer

---

Habit Tracker App/script.js

Ihave added script file for habit tracker app. I got an issue so im adding files one by one.

ISSUE #1376 Created script.js for habit tracker app

---

Habit Tracker App/styles.css

i have added css file for habit tracker app

ISSUE #1376 Created styles.css for habit tracker app

---

Habit Tracker App/index.html

I have added html file for habit tracker app

ISSUE #1376 Created index.html for habit tracker app

---

projects/Habit Tracker App/index.html
projects/Habit Tracker App/script.js
projects/Habit Tracker App/styles.css
projects/Interactive Quiz App/index.html
projects/Interactive Quiz App/script.js
projects/Interactive Quiz App/styles.css
projects/Movie Review Sentiment Analyzer/index.html
projects/Movie Review Sentiment Analyzer/script.js
projects/Movie Review Sentiment Analyzer/styles.css

This pull request introduces an interactive quiz application developed using HTML, CSS, and JavaScript. The application allows users to take quizzes by answering multiple-choice questions and provides real-time feedback on their performance. Key features include dynamic question rendering, score tracking, and user-friendly navigation. The codebase follows best practices for organization and accessibility. Please review the changes and provide feedback for any improvements or adjustments.
screenshot:
please dont mind all the other files got into this. I'm New to this. Please ignore other files. Thank You

ISSUE #1380 Added new project Interactive Quiz App

---

js/app.js

Implemented dark mode persistence using localStorage:
- Added functionality to save and load theme preference using localStorage
- Set initial theme based on saved preference or user’s preferred color scheme
- Updated toggle button to reflect the current theme
- This allows users to maintain their theme preference across sessions, enhancing user experience.
https://github.com/user-attachments/assets/a8831d0d-2759-4ed0-bc32-bd20ff10ce19

#1145 Implemented dark mode persistence

---

index.html

A beautiful and visually attractive responsive website to help users to exchange books and find their own book taste
Solves Issue no #1355

Adding of beautiful website named Swapreads (#1355)

---

projects/Contributor_1/index1.html

[FIX] Contribute Page Button Fix

---

feedback.html

@iamrahulmahato please review and merge it

added back to home button in Feedback page

---

index.html

I have updated the css styles for the button as follows

updated css for button

---

index.html

before
https://github.com/user-attachments/assets/4614e5fe-9153-445a-925b-0321058a8507
after 
https://github.com/user-attachments/assets/e12ff6f0-b122-4b15-b082-e061974274cf
closes issue #1252

improved responsiveness for the website

---

projects/Simple Book Recommendation System/index.html

This pull request introduces a simple Book Recommendation System built with HTML, CSS, and JavaScript. The application allows users to select a genre from a dropdown menu and receive book recommendations tailored to that genre.
Changes Made:
Created a single HTML file that includes all necessary HTML, CSS, and JavaScript code.
Designed a user-friendly interface with a dropdown menu for genre selection.
Implemented JavaScript functionality to display book recommendations based on the selected genre.
Features:
Dropdown menu with various genres (e.g., Fiction, Non-Fiction, Mystery, Fantasy).
Dynamic display of book recommendations using JavaScript.
Responsive design for better usability on different devices.
How to Test:
Open the HTML file in a web browser.
Select a genre from the dropdown …

ISSUE #1451 (solved) Added Simple book recommendation system 

---

css/style.css
js/app.js

Fix Issue: #1069 
Fixed the issue where two "See More" buttons appeared simultaneously during the slider transition. 
Additionally, resolved the bug preventing the thumbnail from updating correctly when the "See More" button is clicked.

Fix Duplicate "See More" Buttons Bug

---

css/style.css
package-lock.json

Gave a blur to the background to add more clarity for the headings

Added blur to the background

---

projects/Virtual Business Card/index.html

This project is an interactive virtual business card built using HTML, CSS, and JavaScript within a single file. It features a smooth card-flip animation, allowing users to toggle between the front (name) and back (contact details) with a click. The card includes clickable links for email, phone, and LinkedIn profile, providing a compact and modern way to share professional information. Designed with sleek styling and minimal interactivity, this project demonstrates how to combine structure, presentation, and logic seamlessly in web development.

ISSUE #1492 (solved) Added Virtual Business Card Project

---

index.html
project_showcase/contributor.css
project_showcase/contributor.html
project_showcase/contributor.js

Hello, PR
Add new feature - #1455
Add Contributors page done -
https://github.com/user-attachments/assets/44016e47-6b6d-44ae-aea4-b14b5af44eb1
Page link in footer -

Add a new contributors page done ! #1455

---

projects/Emoji Translator/index.html
projects/Emoji Translator/script.js
projects/Emoji Translator/style.css

I have created a new project called Emoji Translator that lets user translates words of their text/sentence into corresponding emojis. Its working is shown below:
fixes issue #1473 
https://github.com/user-attachments/assets/41475289-4b4e-4e9d-a20c-4f55273838e9

added emoji translator project

---

projects/Text editor/index.html

This pull request introduces a new feature to the text editor that allows users to undo and redo their text changes seamlessly. The implementation includes:
Undo Button: Users can revert to the previous text state, enabling easy correction of mistakes.
Redo Button: Users can restore the text state after an undo action, providing a smooth editing experience.
State Management: Utilizes an array to maintain the history of text changes and a separate stack for redo operations.
Key Changes:
Added undoBtn and redoBtn to the UI for user interaction.
Implemented event listeners for input changes, undo, and redo actions.
Updated the styling to enhance the user experience.

ISSUE #1495 (solved) Added Text Editor with Undo and Redo Functionality

---

projects/CSS-Animations-Playground/index.html
projects/CSS-Animations-Playground/script.js
projects/CSS-Animations-Playground/styles.css

How the Project Works:
HTML Structure:
The HTML file contains a demo element (a green square) and various controls (sliders and a dropdown) to change the properties of the animation (duration, delay, easing, and iterations).
CSS Styling and Animations:
The CSS file defines basic styles for the layout, the demo element, and its animation using CSS transition properties. These transitions will be dynamically adjusted using JavaScript.
JavaScript Logic:
The JavaScript file listens for changes in the user inputs and dynamically updates the CSS properties for the demo element. Clicking on the element toggles its animation effect.

Added css-animations-playground

---

projects/Personal Diary/index.html

This pull request introduces the Personal Diary Application, a simple web-based diary that allows users to create, view, and delete diary entries. The application leverages HTML, CSS, and JavaScript, and it uses the browser's local storage to persist user entries across sessions.
Features:
Add Diary Entries: Users can write and save new diary entries using a text area. The entries are stored in local storage, ensuring they are retained even after refreshing the page.
View Past Entries: All previously saved entries are displayed on the page, allowing users to revisit their past thoughts and reflections.
Delete Entries: Users can delete any entry they wish, which updates the local storage accordingly.
Technical Details:
HTML: The structure of the diary application is defined using semantic …

ISSUE #1509 (solved) added Personal Diary App Project 

---

number_guessing_game.py

**Changes**: Improved number guessing game by adding new features such as input validation difficulty levels, a dynamic hint system, and a seamless play-again option, making the game more engaging and challenging.
**Fixes**: Issue #1524

Improvement in number_guessing_game

---

projects/Display_Test/index.html
projects/Display_Test/script.js
projects/Display_Test/style.css

Hi Rahul ,
I have contributed in this project , in a program Display_test .. 
A very good program , but there is some issues with functioning and Features , so I updated the features , enhance the UI and made it responsive and complete this program , I wish you can merge my pull request .. I want this to merge form GSSOC contribution .
Issue No. - 1466
The features I added in it - 
1. Expanded Color Palette: Add more colors to the selection.
2. Current Color Display: Show the currently selected color's hex code.
3. Reset Button: Allow users to reset the background to the default color.
4. Smooth Transitions: Add smooth background color transitions.
5. Responsive Design: Ensure the website looks good on all devices.
6. Custom Color Picker: Let users add their own colors.
7. Copy to …

#1466 Display_test UI enhancement and features Added 

---

projects/Personal Blog Website/index.html

This pull request adds a personal blog website that enables users to create, view, and delete blog posts using HTML, CSS, and JavaScript.
Features
Create Posts: Users can add new blog posts with titles and content.
View Posts: Displays a list of all created posts.
Delete Posts: Users can remove posts easily.
Implementation
HTML: Structure with header and sections for posts.
CSS: Simple styling for a clean layout.
JavaScript: Dynamic post management, including rendering, adding, and deleting

ISSUE #1445 (SOLVED)Created Personal Blog Website 

---

projects/bmi calculator/index.html
projects/bmi calculator/javascript.js
projects/bmi calculator/style.css

Hey this is the changes I have done for this website - 
The following improvements have been made to the BMI page:
1. Bug Fix: Corrected an issue with BMI calculation for accurate results.
2. Unit Conversion: Added unit options to facilitate easy conversion between weight and height for BMI calculation.
3. BMI Tips: Provided personalized tips and advice based on the calculated BMI value.
4. UI Enhancements: Improved the user interface for a more polished look.
5. Animations: Added animations to make the page more interactive and visually appealing.
6. Responsive Design: Made the page responsive, ensuring it works seamlessly across various device sizes.
I hope you liked My work 
I work very hard 2-3 days for this change and I want Gssoc level 2 or 3 tag , I hope you like my work

#1536 BMI calculator Bug fix and ui enhancement

---

faq.html
index.html

#1538
https://github.com/user-attachments/assets/1be71be9-74d8-4d92-b0e4-6b98e49454aa
Welcome to the FAQ page for the Master Web Development repository! Here, you’ll find answers to the most common questions about our collection of frontend projects designed to elevate your skills as a developer. Whether you’re curious about the technologies we cover, the types of projects available, or how to get the most out of this resource, our FAQ section is here to provide clarity.
Explore topics such as HTML, CSS, and JavaScript. This page aims to support your learning journey, ensuring you have all the information you need to successfully navigate and utilize the projects within the repository. If you have any further questions, feel free to reach out!

successfully added FAQ page

---

index.html

Hello, PR
Fixed issue - #1457
Add new feature - Translation Tool
https://github.com/user-attachments/assets/0126e848-1905-43d6-8279-532690fbbeee

Add Translation Tool done ! #1457

---

feedback.html
script.js
style1.css

https://github.com/user-attachments/assets/1133271c-098c-41da-b2b9-2ee2c25c6f7f
Added rating feature also changes the ui of feedback form plz review it @iamrahulmahato

Fix #1507 Add rating feature also changes the ui of feeback form

---

projects/Pixel Art Creator/index.html

This PR introduces the Pixel Art Creator project, providing an interactive way for users to design pixel art using a 16x16 grid. Users can select colors through a color picker, click on cells to paint them, and reset the canvas to start over. This project demonstrates DOM manipulation, event handling, and dynamic grid layout using HTML, CSS, and JavaScript.

ISSUE #1542 Added New Project Pixel Art Creator 

---

README.md

Added GitHub Repository Stats to README.md  <issue #1558 reosolve>
**pls merge this pr ASAP!!!**

Added GitHub Repository Stats to README.md

---

projects/Wordle Game/index.html
projects/Wordle Game/script.js
projects/Wordle Game/style.css

Issue Number: #1520
Description of Changes:
Added Functionality to the On-Screen Keyboard: The keyboard will now only become visible after clicking the 'Show Keyboard' button, which will aid in faster page loading.
Bug Fixes: Resolved issues where keyboard keys were not functioning and inputs were not being registered in the input box.
Code Refactoring: Enhanced code readability and maintainability by adding comments and adhering to camelCase conventions.
Manual Testing: Conducted manual testing on Chrome, Edge, and Firefox to ensure the new features operate as intended.

Issue: #1520 Added Functionality to the on-screenKeyboard in wordleGame 

---

index.html
privacy.html

**Title:** Fixed Broken Privacy Link in Footer and Created Privacy Page
**Description:**  
This PR addresses the issue of a broken Privacy Link in the footer by creating a dedicated privacy page. 
**How I Solved It:**
- Identified the broken link in the footer of the website.
- Created a new Privacy Policy page to comply with data protection regulations.
- Updated the footer to link to the new Privacy Policy page.
- Ensured all links are functioning correctly.
Video 
https://github.com/user-attachments/assets/4a91970d-9381-4322-903e-6903e540da55
**Technologies Used:**
- HTML
- CSS
- JavaScript

Fixed Broken Privacy Link in Footer and Created Privacy Page 📨

---

projects/SignatureMakingSite/index.html
projects/SignatureMakingSite/script.js
projects/SignatureMakingSite/style.css

I have created a Signature App that allows users to draw their signatures directly on the canvas. Users can customize their signatures with different styles and colors. Once they are satisfied with their signature, they can download it as an image file for their use. issue no #1526

Created the signature app

---

projects/Image To ASCII Art Converter/index.html

This pull request introduces a unique Image to ASCII Art Converter application that transforms uploaded images into ASCII art. The project leverages JavaScript to process the pixel data of images and convert them into character-based representations.

ISSUE #1587 Added new project image to ascii art generator

---

projects/Real-Time Face Direction Detector/index.html

This pull request introduces a Real-Time Face Direction Detector web application that uses TensorFlow.js and the WebRTC API to track the user’s facial position through the webcam. The app identifies whether the user is looking left, right, or straight by analyzing key facial landmarks.

ISSUE #1589 (solved) added new project Real-Time Face Direction Detector

---

projects/Face Expression Classifier/index.html

This pull request introduces a Real-Time Face Expression Classifier web application that utilizes TensorFlow.js and the webcam to detect facial expressions. The app provides real-time feedback on whether the user appears happy, sad, surprised, or neutral by analyzing facial landmarks.

ISSUE #1595 added new project Face Expression Classifier

---

projects/Rock Paper Scissors/Styles.css
projects/Rock Paper Scissors/index.html
projects/Rock Paper Scissors/script.js

debugged the rock paper scissor game .. fix the issue with computers choice and ou choice , ui enhancement and visual effects to show what both the user choose .. 
also made the site responsive so that it can be used in website .. 
I hope you like my work , as a debugger and open source contributor its pleasure to work with you .. please accept it as gssoc contribution from level 2 or 3 .. I hope you like my work
after -

#1635 Rock paper scissor game big fix, UI Enhancement 

---

css/style.css
index.html

Issue no : #1562 
This pull request introduces a new feature that adds a clickable **Search Button** beside the existing **Search Input Box**. The button provides an intuitive way for users to trigger a search action, complementing the "Enter" key functionality that may already exist.
- Added a new **Search Button** element next to the search input field.
- Updated the CSS for proper alignment and spacing between the input box and the button.
- The button triggers the same search function that is invoked when pressing the "Enter" key inside

Pull Request: Add Search Button Next to Search Input Box

---

projects/2048 Game/index.html

Issue: #1640
- Fixed Spell Typo in 2048 Game

[BUG] Fixed 2048 Game Messages

---

index.html

issue #1620 
**Description**
In this update, I've redesigned the feedback form with a more modern and user-friendly UI, enhancing both its visual appeal and functionality. The new design is fully responsive, ensuring that the form adjusts smoothly across different devices and screen sizes. The layout has been improved for better readability and ease of use, providing a more streamlined experience for users submitting feedback. These changes contribute to a cleaner, more engaging interface that improves overall usability and accessibility.
before:
after:
https://github.com/user-attachments/assets/66f70eb9-97a1-485d-a02e-481eda3f8561

 Improve UI Design of Feedback Form

---

index.html
projects/Habit tracker/index.html
projects/Habit tracker/script.js
projects/Habit tracker/styles.css

I've added the new project habit tracker.
issue no.:  #1583 
https://github.com/user-attachments/assets/acf43190-f666-4c53-b8fe-3a12179ab4ad

Added the new project habit tracker

---

feedback.html
style1.css

link feedback form to home page and add icon in feedback form
Issue : #1561 
Before 
https://github.com/user-attachments/assets/9c62af73-be16-40b9-b986-fad350de772a
After :
https://github.com/user-attachments/assets/fc5262ce-302d-4c8a-aae1-1d49b8f2bcbb

Resolve issue issue #1561

---

index.html
projects/Creative writing/index.html
projects/Creative writing/script.js
projects/Creative writing/styles.css
projects/Habit tracker/index.html
projects/Habit tracker/script.js
projects/Habit tracker/styles.css

I've created and added a new project named creative writing prompt generator.
issue no. : #1652 
https://github.com/user-attachments/assets/1b546f4c-8a88-4220-a51b-b89817dcced6

Creative writing prompt generation 

---

projects/AI-Powered Doodle Classifier/index.html

This pull request introduces an AI-powered doodle classifier using the Canvas API and TensorFlow.js. Users can draw sketches directly on the canvas, and the model predicts their doodles in real-time, providing an engaging and interactive experience.

ISSUE #1655 solved Added AI powered doddle classifier

---

projects/ Project: Voice-Controlled Flashcards Quiz/index.html

This pull request introduces a Voice-Controlled Flashcards Quiz application using the Web Speech API. The quiz allows users to answer questions verbally and provides real-time feedback, creating a hands-free and interactive learning experience.

ISSUE #1700 (solved) Added new project

---

projects/Ambient Color Light/index.html

This pull request introduces an Ambient Color Light Simulator that dynamically changes the background based on the current time of day. The goal is to simulate natural lighting transitions (morning, afternoon, evening, and night) using smooth color shifts, providing a calming and immersive experience for users.

ISSUE #1702 (solved) added new project

---

projects/ Emoji Mood Journal with Local Storage/index.html

This pull request introduces the Emoji Mood Journal, a simple yet effective web-based journal where users can log their mood daily using emojis and notes. The entries are stored in the browser’s Local Storage, ensuring that users can access their mood history even after refreshing or closing the page.

ISSUE #1713 Added new project

---

projects/Gravity Switch/index.html
projects/Gravity Switch/script.js
projects/Gravity Switch/styles.css

Issue #1715 Solved -
🔴 Title:
Gravity Switcher
More changes can be made it to be amazing. It's in it base stage.
🔴 Tech Stack:
HTML5: Structure of the game
CSS3: Styling and layout
JavaScript: Game logic and functionality
Canvas API: Rendering graphics
🔴 Objective:
The objective of the Gravity Switcher game is to navigate a player character through a dynamically changing environment by switching the direction of gravity to collect items and score points while avoiding boundaries.

Issue:- 1715 Solved :- Added Gravity Switch Game using HTML5

---

projects/Virtual Pet Time Machine/index.html
projects/Virtual Pet Time Machine/script.js
projects/Virtual Pet Time Machine/styles.css

Issue :- #1719
🔴 Title: Virtual Pet Time Machine
🔴 Tech Stack:
HTML5
CSS3
JavaScript
🔴 Objective: To nurture a virtual pet that can time-travel through different eras, age over time, and unlock unique skills based on player choices, enhancing the pet's development and overall happiness.
🔴 Summary: Virtual Pet Time Machine is an interactive game that allows players to care for a virtual pet named Fluffy. Players can travel through various eras, such as Prehistoric, Ancient Egypt, Medieval, and Future, each offering unique skills and experiences. As the pet ages with each time travel, players can make choices that influence its development,

Issue :- 1719[Solved]- Added Virtual Pet time machine

---

README.md

#1631
**Description**: 
This pull request aims to improve the `README.md` file by adding a comprehensive troubleshooting section and making corrections to existing content. 
**Changes Made**:
- **Troubleshooting Section**: 
- Added detailed steps to help users address common issues during setup and usage, including:
- Dependency conflicts and installation steps.
- Common setup issues and environment configurations.
- Platform-specific error resolutions (Windows, Linux, macOS).
- Solutions for common errors such as "Module not found" and "Permission denied."
- Debugging tips for better error logging and debugging procedures.
- **Corrections**:
- Fixed typos and inconsistencies in the project listings and descriptions, ensuring clarity and accuracy throughout the document.
**Purpose**: 
The …

Troubleshooting & Corrections

---

projects/KFC Ordering Chatbot/Readme.md
projects/KFC Ordering Chatbot/main.py

@iamrahulmahato  please merge this

add initial files

---

Web-Based Image Resizing Tool/method.html

Header Navigation, User Instructions , FAQs, feedback, contact us, crop the image, change theme, Footer Section

updated method.html #1611

---

projects/Pipe Dream Game/index.html
projects/Pipe Dream Game/script.js
projects/Pipe Dream Game/style.css

Issue #1705 
I have successfully added the Pipe Dream Game
https://github.com/user-attachments/assets/a4896785-78f9-43fe-8e08-ecd0f43fc5c4

#1705 Added Pipe Dream Game

---

footer.css
index.html

Improved UI OF footer add hovering effects  I resolved the conflicts also first fork the website and then mad chnage plz merge it....
@iamrahulmahato

Fix issue #1504 Improve footer add hover effects

---

projects/Clock/index.html
projects/Clock/style.css

Enhanced the UI (adjusted the header and some tweaks in fonts and glass effects) of the liveclock and added some more timezones of major cities. #347

Modified and Enhanced the UI and timezones of the Live Clock. #347

---

css/style.css

dark mode update

---

projects/projectWebpage/pro.html
projects/projectWebpage/style.css

this is a business webpage template

---

index.html

there i changed the image link from the previous link

Fixed issue with feature image link

---

index.html
test.html
welcometestimonials.html

Master Web Development is an open-source platform designed to empower developers by enabling them to contribute to real-world web development projects. Whether you're a beginner or an experienced coder, this platform provides a collaborative environment to enhance your skills, build a portfolio, and make meaningful contributions to the community.
Here's a description you can use for your GitHub repository:
Master Web Development | Open-Source Contribution Platform
Master Web Development is an open-source platform designed to empower developers by enabling them to contribute to real-world web development projects. Whether you're a beginner or an experienced coder, this platform provides a collaborative environment to enhance your skills, build a portfolio, and make meaningful contributions …

Added Testimonials page and quick links in footer

---

projects/Image Editor/image-placeholder.svg
projects/Image Editor/index.html
projects/Image Editor/script.js
projects/Image Editor/style.css

Added Image Editor

---

projects/Save Text As File/index.html
projects/Save Text As File/script.js
projects/Save Text As File/style.css

Added new project Save Text as File

---

Ping-Pong-Game/index.html
Ping-Pong-Game/script.js
Ping-Pong-Game/styles.css

A simple Ping Pong game implemented using HTML, CSS, and JavaScript. Players control paddles using keyboard inputs to keep the ball in play and score points. For first player W and S and for second Up(arrow key) and Down(arrow key) used to control paddles. After any one score point, ball is reset and scoreboard of each players displayed

Ping pong game implemented using HTML, CSS & JS

---

visi.css

Kept it to the sidebar

---

css/style.css
index.html

This pull request addresses the following enhancements for the hero section of the application reported in [#1739](https://github.com/iamrahulmahato/master-web-development/issues/1739):
Changes Made
- Button Alignment: Aligned the "Go to Challenges" and "View Source Code" buttons in a single row. This adjustment provides a more consistent and organized layout, making it easier for users to find and interact with these call-to-action buttons.
- Added hover effects with box shadow in both the buttons
previous status
Current status
https://github.com/user-attachments/assets/d876e9a1-3e49-4dfb-829b-10e8d263835b

Fix Hero Section Visibility and Button Alignment [#1739]

---

AlgorithmVisualizer/heapsortvisualizer.py
AlgorithmVisualizer/timecomplexity1.py

Title: Adding Sorting Algorithm Visualizer with Time Complexity
Tech Stack:
Frontend/UI: Streamlit
Programming Language: Python
*I have also added the time complexity visualizer which shows the heap sort algorithm technique step by step , this is an additional package to this project.*
Objective:
To create an interactive tool that visualizes the HeapSort algorithm, providing users with an intuitive understanding of the sorting process. This application includes a user-friendly interface that allows users to experiment with HeapSort in real time, visualizing each step in the sorting process.
Summary:
The Sort Algorithm Visualization Tool is a Streamlit-based web application designed to offer an engaging way to learn and interact with both the top-down and bottom-up approaches of the …

Adding Sorting Algorithm Visualizer Step by Step

---

projects/Calculator/index.html
projects/Calculator/style.css

Calculator's Key Format was updated to match a standard format. A placeholder text '0' was added to the scientific calculator display screen. Matrix and Functions buttons sizes and format was fixed. #348

Calculator's Key Format Updated and Maxtrix and Function buttons fixed. #348

---

projects/Color Sequence Memory Game/index.html
projects/Color Sequence Memory Game/script.js
projects/Color Sequence Memory Game/style.css

Issue #1817
@iamrahulmahato I have successfully added  Color Sequence Memory Game. Kindly , refer the output video below:
https://github.com/user-attachments/assets/14a25b9c-61b0-4085-8e58-10c9f1141777

#1817 Added the Color Sequence Memory Game

---

projects/Travel Bucket List/index.html
projects/Travel Bucket List/script.js
projects/Travel Bucket List/styles.css

Solves:- #1858:
🔴 Title: Travel Bucket List Web App
🔴 Tech Stack:
HTML
CSS
JavaScript
🔴 Objective: To create an interactive travel bucket list web application that allows users to add, edit, categorize, and delete travel destinations while persisting their data across sessions using local storage.
🔴 Summary: The Travel Bucket List Web App is a user-friendly platform where individuals can manage their travel aspirations. Users can input destinations, choose categories (such as "Want to Visit" or "Visited"), and edit or delete items as needed. The application features a responsive design with a clean layout, making it easy to navigate.

Issue:- #1858 Solved :- Travel Bucket List

---

index.html

Fixes #1758  @iamrahulmahato I have added share button . 
**Before** 
**After**

Sharebutton added

---

CONTRIBUTING.md

I've made some enhancements to including a dedicated section for project organization, a detailed pull request process, and clearer guidelines for issue reporting. I hope you find these changes beneficial.
Could you please add the labels "gesso-ext" . Thankyou !

FIXES #1766 Documentation: UPDATE Of Contributing.md

---

README.md

**Closes: #1738 **
To improve the contributor section, we aim to make it more organized and user-friendly. This will involve clearly listing all contributors with their roles, contributions, and social links, making it easier for users to recognize and connect with them.
**Issue_Reference: #1738**
---

Enhance and Structure the Contributor Section 

---

index.html

The issue was mainly with HTML tags:
- not colosed tags
- closing tag without an opening tag
- and some redundant elements
I also fixed the indentation of the index file.

FIX: fix layout issues

---

index.html

Fixes #1757 @iamrahulmahato Extra share Button removed and also corrected the misdisplaying code.
**Before**
**After**

Extra share Button removed and also corrected the misdisplaying code

---

index.html

Add FAQ Section to the Website.

---

projects/AI BusinessWebpage/pro.html
projects/AI BusinessWebpage/style.css

added a ai business webpage

---

Mood Board Generator/index.html
Mood Board Generator/script.js
Mood Board Generator/style.css
rock-paper-scissors/index.html
rock-paper-scissors/script.js
rock-paper-scissors/style.css

Name : Vyom Chaturvedi
Participant Role: GSSOC
vyomchaturvedi31@gmail.com

Mood board generator

---

Mood Board Generator/index.html
Mood Board Generator/script.js
Mood Board Generator/style.css
rock-paper-scissors/index.html
rock-paper-scissors/script.js
rock-paper-scissors/style.css

Name :Vyom Chaturvedi 
Participant Role ( GSSOC)
vyomchaturvedi31@gmail.com
GirlScript Summer of Code contributor

Added Rock-Paper-Scissors game feature

---

projects/Blog/index.html

Created a blog web app using html, css and javascript
closes: #1003

feature: created blog app

---

projects/Color Sequence Challenge Game/index.html
projects/Color Sequence Challenge Game/script.js
projects/Color Sequence Challenge Game/style.css

Issue #1913
@iamrahulmahato I have successfully added the Color Sequence Challenge Game.

#1913 Added Color Sequence Challenge

---

index.html

Issue no. #1931 
Added the navigation in footer of the page
https://github.com/user-attachments/assets/ec832564-de83-4aff-acb0-0705a190b695

Added navigation links in the  footer of the home page

---

css/style.css
index.html
js/app.js

Here's the screenshot:
Resolved issue #1742

Dark mode text color updated

---

projects/Shape Shifter Game/index.html
projects/Shape Shifter Game/script.js
projects/Shape Shifter Game/style.css

Issue #1935
I have added the shape shifter game successfully . 
@iamrahulmahato Kindly, review and merge the PR. Thanks :)

#1935 Added the Shape Shifter game

---

index.html

**removed these lines of code:** 
```html
<div class="thumbnail">
<div class="item">
</div>
</div>
```
this caused the image "air ballon game.jpg" to overlap with the rest
fixes issue #1925

removed the div class thumbnail

---

js/app.js

issue #1942 
added js code which is missing now running smooth 
@iamrahulmahato  sir pls see this pr & merge 
if possible give me level 2 label !!!
both mode working fine !!!

fix the bugs theme switcher toggle 

---

index.html
projects/iRadio/index.html
projects/iRadio/script.js
projects/iRadio/style.css

Add: Radio Stations to Listen songs #1943

Radio Stations to Listen songs #1943

---

Bloom filter visualizer/app.py
Bloom filter visualizer/templates/index.html

A Bloom Filter Visualizer is a tool that demonstrates how a Bloom filter, a probabilistic data structure, stores and checks membership information with minimal memory usage. In the visualizer, elements are processed through multiple hash functions, which set specific bits in a bit array. When querying the filter, these hash functions check if certain bits are set, indicating whether an element is "possibly in the set" or "definitely not in the set." The visualizer helps users observe how hash collisions can cause false positives (when the filter says an item is in the set when it's not) and showcases the Bloom filter's space-efficient design, making it suitable for large-scale applications like database indexing and network filtering.
ISSUE NO:#1902

Bloom filter visualizer

---

index.html

Hello, PR
Add new feature - #1905
Add a pop up dialog box for Polls/Survey done properly -
https://github.com/user-attachments/assets/da6f0503-07d3-482e-a8c2-931db04c0749

Add a pop up dialog box for Polls/Survey done ! #1905 🌟🌟🌟 

---

projects/Rhythm Catcher Game/index.html
projects/Rhythm Catcher Game/script.js
projects/Rhythm Catcher Game/style.css

Issue #1940
@iamrahulmahato I have successfully added Rhythm Catcher Game . Kindly merge the PR . Thanks :)

#1940 Added Rhythm Catcher Game

---

footer.css

fixed the overlapping text issue in the footer section and created a clean and well-formatted footer.
resolved #1965

modified footer.css

---

projects/Echo Hunt Game/index.html
projects/Echo Hunt Game/script.js
projects/Echo Hunt Game/style.css

Issue #1956
@iamrahulmahato I have successfully added Eco Hunt Game . You can merge the PR.... Thanks :)

#1956 Added the Eco Hunt Game

---

Ping-Pong-Game/styles.css

Modify the position of the Ping-Pong-Game game panel to the middle of the vertical orientation of the screen

modify Ping-Pong-Game/style.css

---

projects/Skill Swap Market Place/index.html
projects/Skill Swap Market Place/script.js
projects/Skill Swap Market Place/styles.css

SOLVES - #1977 
🔴 Title:
Skill Swap Marketplace
🔴 Tech Stack:
Frontend: HTML, CSS, JavaScript
Development Tools: Visual Studio Code, Git
🔴 Objective:
To create an interactive web application that allows users to offer their skills in exchange for learning new skills from others, fostering a community of shared knowledge and personal growth.
🔴 Summary:
The Skill Swap Marketplace is a user-friendly web application where individuals can connect based on their skill sets. Users can post what skills they offer and what skills they wish to learn, creating a dynamic exchange platform.

Issue Solved - #1977 - Added skill swap market place

---

contact.html

Updated the Name and Email field of contact us page

---

projects/AI Pet Name Generator/index.html
projects/AI Pet Name Generator/script.js
projects/AI Pet Name Generator/styles.css

🔴 Title:
AI Pet Name Generator
🔴 Tech Stack:
HTML: Structure the web application
CSS: Style the application for a user-friendly interface
JavaScript: Implement the logic for generating pet names based on user inputs
🔴 Objective:
To create an interactive web application that suggests creative and personalized names for pets based on user-defined habits, genres, and specific starting or ending letters, enhancing the pet naming experience.
🔴 Summary:
The AI Pet Name Generator is a web application designed to help pet owners find the perfect name for their furry friends. Users can input the pet's habits or genre (e.g., playful, adventurous) and specify starting and ending letters to filter name suggestions.

Issue #1984 SOlved :- Added AI Pet Name Generator

---

projects/Dream Journal/index.html
projects/Dream Journal/script.js
projects/Dream Journal/styles.css

🔴 Title:
Interactive Dream Journal
🔴 Tech Stack:
HTML: For structuring the web application.
CSS: For styling and creating a visually appealing user interface.
JavaScript: For implementing interactive functionality and managing data.
Local Storage: To store dream entries in the user's browser, allowing persistence across sessions.
🔴 Objective:
To create an engaging web application that allows users to log and reflect on their dreams. The journal will enable users to record their dreams along with the date, view past entries, and analyze patterns, enhancing their understanding of their subconscious experiences.
🔴 Summary:
The Interactive Dream Journal is a web application designed to help users document their dreams in a simple and intuitive way. Users can enter dream descriptions along …

Issue Solved #1986 - Added Dream Journal

---

projects/Interactive Map for Mythical Creatures/index.html
projects/Interactive Map for Mythical Creatures/script.js
projects/Interactive Map for Mythical Creatures/styles.css

🔴 Title:
Interactive Map of Mythical Creatures
🔴 Tech Stack:
HTML: For structuring the web application.
CSS: For styling the user interface and map.
JavaScript: For interactive functionality and handling data.
Leaflet.js: A library for creating interactive maps.
🔴 Objective:
To develop an engaging web application that allows users to explore mythical creatures from various cultures around the world. Users can interact with a map, view details about different creatures, and learn about their significance in folklore.
🔴 Summary:
The Interactive Map of Mythical Creatures is a web application designed to provide users with an immersive experience exploring legendary creatures from diverse cultures. By leveraging the Leaflet.js library, the application presents an interactive map marked with …

Issue #1988 Solved :- Added Mythical Creatures Map

---

projects/Codebreaker Game/index.html
projects/Codebreaker Game/script.js
projects/Codebreaker Game/style.css

Issue #1968
Successfully added the codebreaker game
@iamrahulmahato Kindly merge this PR .. Thanks :)

#1968 Added Codebreaker game

---

projects/visualization/index.html
projects/visualization/script.js
projects/visualization/styles.css

This dashboard provides a comprehensive visual representation of various data insights using five distinct charts: Age Distribution, Gender Distribution, Citizenship Distribution, Fatalities Over Time, and Fatality Trends for Top Places. Each chart is rendered using the Chart.js library, allowing for an interactive and responsive experience. The layout is organized in a grid format for easy navigation, ensuring that users can quickly analyze demographic and event-related data. With clear titles and labels, the dashboard aims to enhance data understanding and facilitate decision-making. The charts automatically adjust to different screen sizes, making them accessible on various devices.

Added a project folder called visualization

---

Convex hull visualizer/Readme.md
Convex hull visualizer/code.py

The Convex Hull Visualizer is a tool designed to illustrate the convex hull algorithm by generating the smallest convex boundary that can enclose a given set of points. By visualizing how the algorithm constructs the hull step-by-step, this tool helps users understand and explore the geometric properties and computational aspects of convex hull formation. It’s ideal for students, researchers, or anyone interested in computational geometry, providing both interactive and educational insights into this fundamental algorithm.

Convex Hull Visualizer (Issue #2011)

---

projects/Time Traveller Dash/index.html
projects/Time Traveller Dash/script.js
projects/Time Traveller Dash/style.css

Issue #1999
@iamrahulmahato I have successfully added the Time Traveler Dash Game . Kindly , merge the PR .... Thanks :)

#1999 Added the time traveller dash game

---

index.html

Added Scroll to top button at right bottom
enhanced buttons that are visible in both dark and light modes
@iamrahulmahato you can check this!!

Add Scroll to top button and Enhanced buttons (fixes #2018 and #2017)

---

css/style.css
index.html
profile.html
testp.css
testp.js

Hello, PR
Add new feature - #2019
Add a normal user profile page and a profile icon in the home page that redirects to the profile page done -
https://github.com/user-attachments/assets/a6cc35be-bf05-4597-b6ad-5466a5606972

Add a User Profiles page done ! #2019

---

Ping-Pong-Game/index.html
Ping-Pong-Game/script.js
Ping-Pong-Game/styles.css

**Changes Done** : 
1. Improved UI design
2. Improved User Experience by adding buttons such as
• Start
• End
• Pause
• Resume
3. Including instructions of "How to Play" for the user who is new to the game
4. Sound effects
Fixes : https://github.com/iamrahulmahato/master-web-development/issues/1991
Please merge my pull request and label me
@iamrahulmahato

Improved User interface and User experience in Ping Pong game

---

index.html

Hello, PR
Fixed issue - #2015 
done -
Before -

 Remove duplicate text box's in feedback section done ! #2015

---

Shoot Easter Bunny game/index.html
Shoot Easter Bunny game/script.js
Shoot Easter Bunny game/styles.css

📃: Shoot Easter Bunny #2041 
Closes: #2041

 📃: Shoot Easter Bunny #2041 

---

Beer Filling Game/index.html
Beer Filling Game/script.js
Beer Filling Game/styles.css

📃: Beer Filling Game #2040 
Closes: #2040

 📃: Beer Filling Game #2040 

---

The last war game/index.html
The last war game/script.js
The last war game/styles.css

📃: The last war game #2039 
Closes: #2039

 📃: The last war game #2039 

---

Code Snippet Gen/index.html

📃: add code snippet feature #2038 
Closes: #2038

 📃: add code snippet feature #2038 

---

projects/Roman_Number_Converter/index.html
projects/Roman_Number_Converter/script.js
projects/Roman_Number_Converter/style.css

Added project
issue: #2064 
https://github.com/user-attachments/assets/e8501bf9-8c4f-4082-b85b-048dd6f32c22

Roman_number_converter

---

Wall Reaction game/index.html
Wall Reaction game/script.js
Wall Reaction game/styles.css

📃: Wall Reaction game #2079 
Closes: #2079

 📃: Wall Reaction game #2079 

---

footer.css
index.html
js/app.js
visi.js

The alignment of the elements in the Footer is done and the presentation of the Footer elements in Dark Mode are resolved and styling have been done . Invalid Icons in the Hero Section has been removed.
Closes 👍 :
#2025 Invalid Icons in the Footer
#2027 Icons are not needed in the Hero Section
#2054 Dark Mode is not performing fine
Please kindly make this request under gssoc-ext with level 3 as the process is time consuming and lot of efforts has been done. So it's a request to upgrade this to level 3.

Resolved Dark Mode and Footer Issues

---

ATS-SCORE-RECOZNIZER/templates/index.html
Beer Filling Game/index.html
Bloom filter visualizer/templates/index.html
Code Snippet Gen/index.html
ExpenseTracker_App/src/index.html
Habit Tracker App/index.html
Mood Board Generator/index.html
challenges/challengehtml.html
challenges/easycss.html
challenges/hardcss.html
challenges/index.html
challenges/medcss.html
contact.html
faq.html
feedback.html
privacy.html
profile.html
terms.html
test.html
welcometestimonials.html

Added icon in all Pages !!

---

projects/Galaxy Explorer/index.html
projects/Galaxy Explorer/script.js
projects/Galaxy Explorer/style.css

Issue #2036
@iamrahulmahato I have successfully added Galaxy Explorer Game. Kindly, merge the PR ....Thanks :)

#2036 Added the Galaxy Explorer Game

---

README.md

I have implemented a "Back to Top" scroll-up button in the README file to enhance navigation for users. This feature allows users to quickly return to the top of the document, improving overall user experience.
@iamrahulmahato Please review and merge it.

Add "Back to Top" Scroll-Up Button in README

---

index.html

With respect to issue, #2053, I changed the text box color so that the text is visible. 
Before:
After:

Changed color for button text to be visible

---

projects/Deep Sea Diver/index.html
projects/Deep Sea Diver/script.js
projects/Deep Sea Diver/style.css

Issue #2095
@iamrahulmahato I have added the Deep Sea Diver Game .....Kindly, merge the PR....Thanks :)

#2095 Added the Deep Sea Diver Game

---

Pure Html Game/index.html

📃: Pure html game #2081 
Closes: #2081

 📃: Pure html game #2081 

---

projects/Travel Vlog/about.html
projects/Travel Vlog/contact.html
projects/Travel Vlog/feedback.html
projects/Travel Vlog/home.html
projects/Travel Vlog/vlog.html

Fixes: #2057 
I have added the feedback form in travel blog
Before:
After:
https://github.com/user-attachments/assets/eeb3db18-a8a9-4335-8078-ad763d14c061

Add feedback form

---

SpaceBubbleDodger_Game/index.html
SpaceBubbleDodger_Game/script.js
SpaceBubbleDodger_Game/style.css

Added folder of SpaceBubbleDodger Game on main repo.

---

challenges/index.html

i  have added the home button in challenges page and also make it workable.
issue #2122 
i want you to add hacktoberfest label also.
thanks.

home button added

---

profile.html
testp.css

solved issue #2117 
made it mobile responsive

Improved Profile Page Ui

---

index.html

The question is now auto-closing after clicking another question.
https://github.com/user-attachments/assets/60513f78-1c64-44e6-9236-28fa4b7a8c3b

 🛠️FIX : FAQ section's question auto close issue

---

css/style.css
index.html
projects/Realtime-Polling-App/node_modules/.package-lock.json
projects/Realtime-Polling-App/package-lock.json
projects/Realtime-Polling-App/package.json
projects/Swiggy Clone/node_modules/.package-lock.json
projects/Swiggy Clone/package-lock.json
projects/Swiggy Clone/package.json
projects/Travel Vlog/about.html
projects/Travel Vlog/contact.css
projects/Travel Vlog/contact.html
projects/Travel Vlog/feedback.html
projects/Travel Vlog/home.css
projects/Travel Vlog/home.html
projects/Travel Vlog/style.css
projects/Travel Vlog/vlog.css
projects/Travel Vlog/vlog.html

Fixes: #2128  , #2125 and #2128
In my first commit
Fixes:#2128
Before:
After:

Improve the visibility of text in dark mood

---

activity.css
activity.js
profile.html
recent-activity.html

I added a recent activity page to the profile page.
https://github.com/user-attachments/assets/a13186d4-0653-4992-b041-3eb194c29610

🛠️FIX : Added recent activity page in profile.html

---

index.html

closes : #2123 
i corrected the overlapping of subscribe button upon scrolling in footer section.

corrected the overlapping of subscribe button in footer section .

---

.github/ISSUE_TEMPLATE/documentation.yml

Create the documentation Template for better clarity and usability, especially for new users setting up the project. This improvement aims to simplify the setup process by providing clear instructions and examples.
N/A
This enhancement includes updates to the README and other relevant documentation files to provide new users with a more intuitive and user-friendly setup experience. Clear examples and step-by-step instructions will aid in reducing setup time and confusion.

CREATE DOCUMENTATION TEMPLATE

---

index.html

There are unwanted buttons in the Hero Section that actually are not performing anything and the alignment of the buttons are actually misaligned even if it is wanted then styling is a must and the performance as it was degrading the User Interface and in return, User Experience has been improved now.
Closes:
#2159 Unwanted Buttons in Hero Section

Unwanted Buttons in Hero Section

---

index.html

The Game Cards have been duplicated and even some are actually having different cards content but redirecting to same thing and the duplication leads to redundancy to the Website which makes User Interface inefficient and User Experience as well.
Closes:
#2150 Duplication of Game Cards on Website

Duplication Of Game Cards on Website Resolved

---

MineSweeper_Game/index.html
MineSweeper_Game/script.js
MineSweeper_Game/style.css

added MineSweeper Game project folder on main repo.

---

challenges/index.html

Enhancing the Challenges page
updated home button for index.html
Enhancement Aim :Enhancing the Challenges page
Fixes: #2191 (Enhancing the Challenges page)

Enhancing the Challenges page (Fixes: #2191)

---

projects/InspoMap/index.html
projects/InspoMap/style.css

Fixes: #2183
Changes
https://github.com/user-attachments/assets/51994053-5fa4-4c37-879d-32ebb2be54be
@iamrahulmahato Please review my change I have added the dark theme

Add dark theme

---

Backbone Tetris Game/index.html
Backbone Tetris Game/script.js
Backbone Tetris Game/style.css

📃: add a Backbone Tetris game #2121 
Closes: #2121

 📃: add a Backbone Tetris game #2121 

---

The 3D Cube game/index.html
The 3D Cube game/script.js
The 3D Cube game/style.scss

📃: The Cube 3D game #2211 
Closes: #2211 
Can you please upgrade the level for this wonderfull game. thank you./

 📃: The Cube 3D game #2211 

---

index.html

🔴 Title :Bug
🔴 Bug :Both Scroll to Top button and chat box are coinciding
🔴 Changes :
Fixed the buttons!!
Screenshots 📷

Both Scroll to Top button and chat box are coinciding (Fixed: #2190)

---

footer.css
index.html
projects/BookVerse/index.html

Improve the visibility of social media icon in dark mode

---

projects/BookVerse/index.html

Fixes: #2182 
On clicking on books we will redirect to book verse
@iamrahulmahato Please review my changes

Add detail in book Verse

---

Coloron 3D game/index.html
Coloron 3D game/script.js
Coloron 3D game/style.scss

📃: Coloron 3D game #2213 
Closes: #2213

 📃: Coloron 3D game #2213 

---

Archery Game/index.html
Archery Game/script.js
Archery Game/styles.css

📃: Archery Game #2223 
Closes: #2223

 📃: Archery Game #2223 

---

Valorous Rabbit/index.html
Valorous Rabbit/script.js
Valorous Rabbit/style.scss

📃: Valorous Rabbit #2225 
Closes: #2225 
@iamrahulmahato can you please upgrade my level its a 3d game. :}
thank you

 📃: Valorous Rabbit #2225 

---

projects/Chromatic Memory Test/index.html
projects/Chromatic Memory Test/script.js
projects/Chromatic Memory Test/style.css

Issue #2133
@iamrahulmahato I have added Chromatic Memory Game successfully. Kindly , merge the PR....Thanks :)

#2133 Added Chromatic Memory Game

---

Task Planner/index.html
Task Planner/script.js
Task Planner/style.css

task planner

---

Expense Splitter/index.html
Expense Splitter/script.js
Expense Splitter/style.css

Expense Spilitter

---

projects/Calculator/index.html
projects/Calculator/style.css

Fixes: #2234 
Screen recording of my change:
https://github.com/user-attachments/assets/fbfefafa-c44d-41e8-aae5-22c507aa081e

Add dark mode theme in scientific calculator

---

Pac-Man-Game/README.md
Pac-Man-Game/app.js
Pac-Man-Game/index.html
Pac-Man-Game/style.css

fix #648 
The Pac-Man game is a classic arcade-style web application that allows users to navigate a character around a game area, collecting food items while avoiding ghosts. Users can control Pac-Man using the keyboard's arrow keys, with the goal of maximizing their score by eating as many food items as possible.
Key Features
Interactive Gameplay: Users can control Pac-Man's movement with keyboard inputs to navigate the game area.
Scoring System: Points are awarded for each food item collected, allowing users to track their scores.
Dynamic Food Generation: Food items appear randomly on the game board, providing a different experience each time.
Simple User Interface: A clean layout that focuses on the game experience with real-time score updates.
Responsive Design: Ensures that the game …

Pac-Man Game #648

---

Real time location tracker/README.md
Real time location tracker/app.js
Real time location tracker/package-lock.json
Real time location tracker/package.json
Real time location tracker/public/css/style.css
Real time location tracker/public/js/script.js
Real time location tracker/views/index.ejs

fix #552
This is a real-time GPS location tracking application built with Node.js, Express, and Socket.IO. It allows users to share their location and view the locations of other connected users in real-time.
Real-time location sharing
Multiple user support
Automatic disconnection handling
Node.js installed (version 12.x or higher recommended)
npm (Node Package Manager) installed

Live location tracker #552

---

projects/Calculator/index.html
projects/Calculator/style.css
projects/Tip calculator/index.html
projects/Tip calculator/style.css

fixes: #2236 
My changes:
https://github.com/user-attachments/assets/907c1abc-d1d3-4f53-9aa1-6bbd56fcc14c
@iamrahulmahato  Please review my changes

Add dark mode theme in tip calculator

---

projects/Calculator/index.html
projects/Calculator/style.css
projects/Card-Validator/index.html
projects/Card-Validator/style.css
projects/Tip calculator/index.html
projects/Tip calculator/style.css

Fixes: #2235 
**My change:**
https://github.com/user-attachments/assets/e4430a06-0573-492b-b91f-22ccc9bfec65

Add dark mode theme in card-validator

---

Highway Race Game/index.html
Highway Race Game/script.js
Highway Race Game/style.css

📃: Highway Race Game #2272 
Closes: #2272

 📃: Highway Race Game #2272 

---

Kill the birds game/index.html
Kill the birds game/style.css

📃: Kill the birds game #2274 
Closes: #2274

 📃: Kill the birds game #2274 

---

Color Blast game/index.html
Color Blast game/script.js
Color Blast game/style.css

📃: Color Blast game #2277 
Closes: #2277

 📃: Color Blast game #2277 

---

Unruly Tower Game/index.html
Unruly Tower Game/script.js
Unruly Tower Game/style.css

📃: Unruly Tower Game #2279 
Closes: #2279

 📃: Unruly Tower Game #2279 

---

challenges/index.html

The page was enhanced with improved styling, interactivity, and responsiveness. Key changes include dynamic animations, hover effects on cards and buttons, and a more engaging layout for quiz challenges.
1. **Styling Improvements:**
- Updated background color to vibrant red (`#db1939`).
- Added text-stroke and sliding animation to the title.
- Darker background for `.container` and better spacing.
2. **Quiz Card Design:**
- Added hover effects and shadow for quiz cards.
- Images now fill the card width with `object-fit: cover`.
- Titles have borders and inner shadows for emphasis.
3. **Button Enhancements:**
- Buttons now have hover effects (`background-color change`, `translateY`).
- Consistent modern design with rounded corners and padding.
4. **Responsiveness:**
- Used `flexbox` for …

Enhancing the Quiz page !!

---

css/style.css
navbar.css
projects/Calculator/index.html
projects/Calculator/style.css
projects/Card-Validator/index.html
projects/Card-Validator/style.css
projects/Tip calculator/index.html
projects/Tip calculator/style.css
styles.css

Fixes: #2251 
Before:
After:
https://github.com/user-attachments/assets/683bab3d-616e-4129-b6b7-f07d4d2bb470
@iamrahulmahato Please review my changes

Improve the visibility of master web

---

css/style.css
navbar.css
projects/Calculator/index.html
projects/Calculator/style.css
projects/Card-Validator/index.html
projects/Card-Validator/style.css
projects/Nutrition Chart/Nutrion.html
projects/Tip calculator/index.html
projects/Tip calculator/style.css
styles.css

Fixes: #2237 
**My changes**
https://github.com/user-attachments/assets/e0ee06f8-cd1a-446f-bd43-34b036d4f5a7
@iamrahulmahato Please review my changes

Add dark mode theme in nutrition search

---

faq.html

fixes: #1792
before; can be seen in issue
after:

arrow rotation

---

Glitch text effect/index.html
Glitch text effect/style.scss

📃: Glitch text effect #2281 
Closes: #2281

 📃: Glitch text effect #2281 

---

Minion Eyes/index.html
Minion Eyes/style.css
Minion Eyes/style.js

📃: Minion Eyes portfolio #2324 
Closes: #2324

 📃: Minion Eyes portfolio #2324 

---

Flattastic Pro Color Palette/index.html
Flattastic Pro Color Palette/style.css

📃: Flattastic Pro Color Palette #2326 
Closes: #2326

 📃: Flattastic Pro Color Palette #2326 

---

Drag and drop/index.html
Drag and drop/script.js
Drag and drop/style.css

📃: Drag and drop #2328 
Closes: #2328

 📃: Drag and drop #2328 

---

Cricket game/index.html
Cricket game/script.js
Cricket game/style.css

I have added a cricket game using html , css , javascript .
Game Description :
Score: You accumulate runs by clicking the "Hit the Ball!" button.
Outcome: Each click randomly generates a score between 0 to 6. If the score is 0, a message will indicate that you've been "Out".

Cricket Game

---

index.html

Fixes: #2271 
https://github.com/user-attachments/assets/d36c1314-bab9-4233-a0de-d7d88112b5b1

fix the alignment of cards

---

styles.css

Fixes: #2330 
@iamrahulmahato Please review my changes

Update text color

---

challenges/challengehtml.html

Improved UI of HTML Quiz !!

---

challenges/hardcss.html

Enhancing Quiz page !!!

---

challenges/easycss.html

Improving the UI of easy CSS challenge !!

---

projects/hoverboard/index.html
projects/hoverboard/script.js
projects/hoverboard/style.css

Added new project hoverboard

---

contactus.html
index.html

Issue: #2377 
There is a contact us page added for  improving  the overall user experience by offering multiple communication options and even embedding maps for easy navigation to physical locations.

feat: added a contactuspage

---

Joke creator/index.html
Joke creator/script.js
Joke creator/style.css

#fix 1346
Interactive Buttons: Upgrade the "New Joke" button by adding dynamic hover effects, smooth color transitions, and engaging animations to make it more visually appealing and responsive when clicked.
Animated Result Display: After the calculation is complete, present the result with lively animations, such as playful graphics that animate when revealing the joke for a more entertaining experience.
Background and Theme: Implement a visually appealing background featuring gradients and playful, lighthearted imagery that enhances the overall mood and complements the app's theme.
Custom Fonts and Icons: Select a whimsical, humorous font for titles and results, and incorporate fun-themed icons to enrich the overall design.
Responsive Design: Guarantee that the application is fully …

🧑‍💻 : ENHANCING THE USER INTERFACE OF THE JOKE GENERATOR #1346

---

index.html

#2375 Fixed inconsistent dark mode.
before:
after:

Bug fix: Inconsistent Dark Mode 

---

index.html

The Footer has been revamped and the overlapping of Elements has been solved and the styling of the elements has been done. Even the FAQs section is also revamped and alignment solution is done. The User Interface of the Footer is looking nice in return, enhances the User Experience. And even the pop-up window is also working fine right now.
Closes:
#2160 Mismanagement of Footer

Mismanagement of Footer Resolved

---

footer.css
index.html

The User Interface of Footer as a whole has been solved. The Links and the newsletter section is looking appealing and the user will visit again as the user interface acts as user attraction. The user Experience has been enhanced. Whole footer section has been enhanced.
Closes:
#2143 Inappropriate alignment of Links and newsletter section

Inappropriate alignment of Links and Newsletter section Resolved

---

footer.css
index.html

The Cards alignment has been rectified and the was some space between cards which have been removed. Some of the game cards are repeated that there are a lot of games repeated.
Closes:
#2161 Mismanagement of Cards

Mismanagement of Cards Resolved

---

index.html

The elements of the website was still in dark theme even if clicking theme changing button and stays the elements in dark theme. Now, the elements could be seen in light theme by default.
Closes:
#2358 Dark mode is not working properly

Dark Mode is not working properly Resolved

---

projects/Tic-tac-toe/style.css

Please check if its done or not

Sanyuktha prabhu patch 2

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
.github/ISSUE_TEMPLATE/Documentation.yml
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml

👨‍💻 Description
Updated Issue Template:
I have enhanced the GitHub issue template by adding distinct sections for features, bug fixes, and documentation updates.
This provides contributors with clear guidance on how to categorize their contributions, ensuring better organization and
clarity in project management.
Modified Pull Request Template:
The pull request template has also been refined to align with the new issue structure. This includes prompts for contributors
to summarize their changes effectively, highlight major enhancements, and confirm adherence to project guidelines.
Project Enhancement:
These modifications streamline the contribution process, making it easier for maintainers to review submissions and for
contributors to present their work comprehensively. This ultimately …

Created new ISSUE TEMPLATES !!!

---

challenges/jshard.html

Created JS Hard challenge !!!
